# Numpy Learning
 It is general- purpose array processing package. it provides a high performance mutlidimensional array object, and tools for working with these array. 

# Array vs List
Array stores same type of data types but list can stores different data types

In [2]:

import numpy as np

In [4]:
my_list = [1,2,3,4,5]
type(my_list)

list

In [5]:
my_list

[1, 2, 3, 4, 5]

In [25]:
arr= np.array(my_list)
type(arr)

numpy.ndarray

In [26]:

print(arr)

[1 2 3 4 5]


arr.shape ---> it shows the no of rows and columns

In [27]:
arr.shape


(5,)

In [30]:
## Multinested array 

my_list1 = [1,2,3,4]
my_list2 = [2,4,8,32]
my_list3 = [5,23,12,654]

arr1 = np.array([my_list1,my_list2,my_list3])

arr1


array([[  1,   2,   3,   4],
       [  2,   4,   8,  32],
       [  5,  23,  12, 654]])

In [31]:
arr1.shape

(3, 4)

In [35]:
arr1.reshape(2,6)
## size of array must be same as before

array([[  1,   2,   3,   4,   2,   4],
       [  8,  32,   5,  23,  12, 654]])

In [43]:
arr1[0,3]

np.int64(4)

In [45]:
arr1[0:2,0:2]

array([[1, 2],
       [2, 4]])

In [49]:
arr2 = np.arange(0,10)
# (start, index, gap)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr2 = np.arange(10,30,3)
# (start, index, gap)
arr2

array([10, 13, 16, 19, 22, 25, 28])

In [53]:
np.linspace(0,10,50)
# it makes divides the starting point and ending point into equal points

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [62]:
# copy() function and broadcasting

arr1[2:] = 100
arr[3:]= 200

In [64]:
arr1


array([[  1,   2,   3,   4],
       [  2,   4,   8,  32],
       [100, 100, 100, 100]])

In [65]:
arr


array([  1,   2,   3, 200, 200])

In [66]:
arr1 = arr

In [69]:
arr1

array([  1,   2,   3, 200, 200])

In [70]:
arr1[2:] = 500
arr1

array([  1,   2, 500, 500, 500])

In [ ]:
arr
# arr1 and arr both refercening each other. If any one have any changes it reflects in both array

array([  1,   2, 500, 500, 500])

In [74]:
arr[4:]= 19099
arr

array([    1,     2,   500,   500, 19099])

In [75]:
arr1

array([    1,     2,   500,   500, 19099])

In [81]:
# to preventing this type of issue, use copy function , it makes a another spaces of array

arr1= arr.copy()
arr1[3:] = 34443
arr1

array([    1,     2,   500, 34443, 34443])

In [82]:
arr

array([    1,     2,   500,   500, 19099])

In [84]:
# operations on array
arr1 < 2



array([ True, False, False, False, False])

In [85]:
arr >300

array([False, False,  True,  True,  True])

In [86]:
arr*2

array([    2,     4,  1000,  1000, 38198])

In [87]:
arr%3

array([1, 2, 2, 2, 1])

In [ ]:
np.ones((5),dtype= int)  

array([1, 1, 1, 1, 1])

In [ ]:
np.ones((4,5),dtype=float) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
np.random.rand(3,4)

array([[0.03243452, 0.60170544, 0.70001361, 0.68693773],
       [0.25035602, 0.76068962, 0.12760465, 0.2031091 ],
       [0.76407605, 0.97488969, 0.8957523 , 0.70494816]])

In [95]:
np.random.randn(4,2)

array([[-0.09697254, -0.20506425],
       [ 0.54606384, -0.65340829],
       [ 2.46103956, -0.00702075],
       [-0.64534385,  0.07846833]])

In [ ]:
# randint(from starting point, to ending point, no. of values)

np.random.randint(1,100,8)

array([45, 30, 91, 37, 28, 66, 22, 82], dtype=int32)

In [97]:
np.random.randint(1,100,8).reshape(2,4)

array([[ 5, 92, 40, 12],
       [53, 94, 64, 24]], dtype=int32)