## T test

A T-test is a type of inferential statistic which is used to dertermine if there is a significant difference betwwen the means of two groups which may be be related in certain features.

T-test has 2 types : 1. One sampled T-test
                     2. Two sampled T-test

## One sample T-test

In [1]:
ages = [10,20,32,43,32,54,65,33,23,26,43,21,13,2,42,6,26,28,29,4,32,3,14,26,27,17,19,15,3,53,63,8,4,86,0,70,65,43,32,12]

In [4]:
len(ages)

40

In [5]:
import numpy as np
ages_mean = np.mean(ages)
print(ages_mean)

28.6


In [7]:
samples_size = 10
ages_sample = np.random.choice(ages,samples_size)

In [8]:
ages_sample

array([20, 20,  6, 63, 65, 86, 54, 27, 32, 43])

In [10]:
from scipy.stats import ttest_1samp

ttest,p_value = ttest_1samp(ages_sample,28)

In [12]:
print(p_value)

0.11987694797075388


In [15]:
if p_value<0.05:
    print("we are rejecting the null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis


### Another examples with ages of students of school

In [23]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math

np.random.seed(6)
school_ages = stats.poisson.rvs(loc=18, mu=35, size = 1500)
class_ages = stats.poisson.rvs(loc=18, mu=30, size = 60)

In [19]:
class_ages.mean()

np.float64(46.9)

In [25]:
class_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [31]:
ttest, p_value = stats.ttest_1samp(class_ages,school_ages.mean())

In [28]:
p_value

np.float64(1.139027071016194e-13)

In [29]:
school_ages.mean()

np.float64(53.303333333333335)

In [30]:
if p_value<0.05:
    print("we are rejecting the null hypothesis")
else:
    print("we are accepting null hypothesis")

we are rejecting the null hypothesis


### Two sample T-test with python

The Independent samples t test or 2 sample t-test compares the means of two independent groups in order to determine whether there is statiscal evidence that the associated popular means are significantly different. The independent samples T test is a parametric test. This test is also known as independent t test

In [33]:
np.random.seed(12)
ClassB_ages = stats.poisson.rvs(loc= 18,mu = 33,size = 60)
ClassB_ages.mean()

np.float64(50.63333333333333)

In [41]:
ClassB_ages

array([44, 47, 60, 65, 47, 52, 56, 56, 44, 48, 50, 47, 55, 49, 50, 50, 50,
       41, 53, 47, 39, 50, 52, 43, 53, 51, 59, 53, 51, 46, 41, 53, 63, 53,
       48, 65, 63, 54, 49, 53, 48, 45, 49, 59, 50, 51, 56, 45, 56, 43, 43,
       47, 54, 48, 45, 41, 60, 48, 51, 49])

In [42]:
ttest,P_value = stats.ttest_ind(class_ages,ClassB_ages,equal_var = False)

In [39]:
p_value

np.float64(1.139027071016194e-13)

In [40]:
if p_value<0.05:
    print("we are rejecting the null hypothesis")
else:
    print("we are accepting null hypothesis")

we are rejecting the null hypothesis


### Paired T-test with Python

when you want to check how different samples from the same group are, you can go for a paired T-test

In [46]:
weight1 = [25,30,43,12,45,32,54,6,5,86,64,13,4,7,88,44,32,12]
len(weight1)

18

In [47]:
weight2 = weight1 + stats.norm.rvs(scale = 5, loc = -1.25, size = 18)

In [48]:
weight2

array([30.57926457, 34.91022437, 44.00444617,  7.54295091, 36.86201983,
       35.57873174, 46.3299827 , -1.6228605 , 11.36420881, 92.05941216,
       62.93827982, 10.519014  , -0.57148787,  7.50667769, 84.32984284,
       35.1845637 , 26.93234756, 11.99601605])

In [49]:
weight_df = pd.DataFrame({"Weight_10": np.array(weight1),
                          "Weight_20" : np.array(weight2),
                          "Weight_change" : np.array(weight2) - np.array(weight1)})

In [50]:
weight_df

Weight_10  Weight_20  Weight_change
0          25  30.579265       5.579265
1          30  34.910224       4.910224
2          43  44.004446       1.004446
3          12   7.542951      -4.457049
4          45  36.862020      -8.137980
5          32  35.578732       3.578732
6          54  46.329983      -7.670017
7           6  -1.622861      -7.622861
8           5  11.364209       6.364209
9          86  92.059412       6.059412
10         64  62.938280      -1.061720
11         13  10.519014      -2.480986
12          4  -0.571488      -4.571488
13          7   7.506678       0.506678
14         88  84.329843      -3.670157
15         44  35.184564      -8.815436
16         32  26.932348      -5.067652
17         12  11.996016      -0.003984

In [51]:
ttest, P_value = stats.ttest_rel(weight1, weight2)

In [53]:
p_value

np.float64(1.139027071016194e-13)

In [54]:
if p_value<0.05:
    print("we are rejecting the null hypothesis")
else:
    print("we are accepting null hypothesis")

we are rejecting the null hypothesis
